<?php
/**
 * @file
 * classified_advertising_common.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function classified_advertising_common_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
